let currentLang = "ru";

const translations = {
  ru: {
    myName: "НАТАЛЬЯ АГАПОВА",
    languageSwitch: "switch to english",
    locationExtra: "иннополис, россия",
    contactExtra: "связаться со мной",
    year: "© 2025",
    aboutTitle: "обо мне",
    aboutText: "моя цель — сделать дизайн простым, приятным и креативным",
    portfolioTitle: "мои проекты",
    InnoBookLoversTitle: "INNOBOOKLOVERS",
    InnoBookLoversDesc: "дизайн сайта для курса по фронтенд разработке в университете иннополис. отвечала за ux/ui интерфейс в проекте",
    InnoMedTitle: "INNOMED",
    InnoMedDesc: "прототип приложения innomed был разработан для университета иннополис на курсе по продакт менеджменту. я была в роли владельца продукта и также отвечала за разработку прототипа",
    PostersTitle: "ПОСТЕРЫ",
    PostersDesc: "у меня есть опыт дизайна афиш для мероприятий в казани и иннополисе. мое видение в том, чтобы плакаты были удобочитаемыми и эстетичными",
    ConceptsTitle: "КОНЦЕПТЫ",
    ConceptsDesc: "экспериментальные макеты, сделанные для себя",
    TsarevBarilovaTitle: "ЦАРЁВ & БАРИЛОВА",
    TsarevBarilovaDesc: "дизайн сайта для продажи онлайн курсов по танцам",
    CroissanStudioTitle: "CROISSAN STUDIO",
    CroissanStudioDesc: "продукты, разработанные мной для нейрохудожника - продукта croissan studio: лого, мерч, концепты",
    experienceBlockTitle: "опыт",
    educationBlockTitle: "образование",
    volunteeringBlockTitle: "волонтёрство",
    expCroissan: "croissan studio — студия разработки полного цикла для ии-продуктов (ux/ui и продуктовый дизайнер, фронтенд-разработчик, ai-креатор на проектной занятости, апрель 2025 - ...)",
    expAzimov: "azimovlab — ии-сервис генерации тестов (фронтенд разработчик, февраль – сентябрь 2024)",
    expClearmind: "фриланс — дизайн афиш, сайтов; вёрстка сайтов на заказ (2022 - ...)",
    eduInnopolis: "университет иннополис — бакалавриат: прикладной искусственный интеллект (2026)",
    volTrenirovochnaya: "trenirovochnaya.kzn — организация танцевальных мероприятий в казани (бренд-дизайнер, маркетолог, март 2025 – ...)",
    volInnostreetdance: "innostreetdance — студенческий танцевальный клуб университета иннополис (бренд-дизайнер, маркетолог, декабрь 2022 – ...)",
    footerContact: "связаться со мной"
  },
  en: {
    myName: "NATALIA AGAPOVA",
    languageSwitch: "русская версия",
    locationExtra: "innopolis, russia",
    contactExtra: "contact me",
    year: "© 2025",
    aboutTitle: "about me",
    aboutText: "my goal is to make design simple, pleasing, and creative",
    portfolioTitle: "my projects",
    InnoBookLoversTitle: "INNOBOOKLOVERS",
    InnoBookLoversDesc: "website design for frontend development course at innopolis university. i was responsible for ux/ui design in the project",
    InnoMedTitle: "INNOMED",
    InnoMedDesc: "innomed app prototype developed at innopolis university during a product management course. i was the product owner and created the prototype",
    PostersTitle: "POSTERS",
    PostersDesc: "i have experience designing event posters for kazan and innopolis. my approach is to keep them readable and aesthetic",
    ConceptsTitle: "CONCEPTS",
    ConceptsDesc: "experimental mockups and album covers made for fun",
    TsarevBarilovaTitle: "TSAREV & BARILOVA",
    TsarevBarilovaDesc: "website design for online dance courses",
    CroissanStudioTitle: "CROISSAN STUDIO",
    CroissanStudioDesc: "products developed by me for neuroartist - a project by croissan studio: logos, merch, concepts",
    experienceBlockTitle: "experience",
    educationBlockTitle: "education",
    volunteeringBlockTitle: "volunteering",
    expCroissan: "croissan studio — ai products studio (ux/ui & product designer, frontend developer, ai-creator on project duty, apr 2025 - ...)",
    expAzimov: "azimovlab — ai service for generating tests (frontend developer, feb – sep 2024)",
    expClearmind: "freelance — design posters, websites; web development on order (2022 - ...)",
    eduInnopolis: "innopolis university — bsc in applied artificial intelligence (2026)",
    volTrenirovochnaya: "trenirovochnaya.kzn — organization of dance events in kazan (brand-designer, marketing person, mar 2025 – ...)",
    volInnostreetdance: "innostreetdance — student dance club of innopolis university (brand-designer, marketing person, dec 2022 – ...)",
    footerContact: "contact me"
  }
};

function switchLanguage() {
  currentLang = currentLang === "ru" ? "en" : "ru";

  const map = {
    languageSwitch: "languageSwitch",
    locationExtra: "location-extra",
    contactExtra: "contact-extra",
    year: "year",
    aboutTitle: "about-title",
    aboutText: "about-text",
    portfolioTitle: "featuredTitle",
    InnoBookLoversTitle: "InnoBookLoversTitle",
    InnoBookLoversDesc: "InnoBookLoversDesc",
    InnoMedTitle: "InnoMedTitle",
    InnoMedDesc: "InnoMedDesc",
    PostersTitle: "PostersTitle",
    PostersDesc: "PostersDesc",
    ConceptsTitle: "ConceptsTitle",
    ConceptsDesc: "ConceptsDesc",
    TsarevBarilovaTitle: "TsarevBarilovaTitle",
    TsarevBarilovaDesc: "TsarevBarilovaDesc",
    CroissanStudioTitle: "CroissanStudioTitle",
    CroissanStudioDesc: "CroissanStudioDesc",
    project1Desc: "project1-desc",
    experienceBlockTitle: "experience-block-title",
    educationBlockTitle: "education-block-title",
    volunteeringBlockTitle: "volunteering-block-title",
    expCroissan: "exp-croissan",
    expAzimov: "exp-azimov",
    expClearmind: "exp-clearmind",
    eduInnopolis: "edu-innopolis",
    footerContact: "footer-contact",
    myName: "store-name",
    volTrenirovochnaya: "vol-trenirovochnaya",
    volInnostreetdance: "vol-innostreetdance",
  };

  for (const key in map) {
    const el = document.getElementById(map[key]);
    if (el) el.textContent = translations[currentLang][key];
  }
}
